### ISSUE TITLE
Username error when launching homebridge

### ISSUE THREAD

**Issue by JSTYL** [jnewland/SmartThings#5]
I attempted to follow the guide here - (http://www.automatedhome.co.uk/apple/smartthings-raspberry-pi-homebridge-siri-homekit-controlled-smart-home.html) with the exception of leaving the default US settings as is, however when I reached the point to launch homebridge I'm getting the following error below.

Please advise with any help or suggestions, Thanks.

jstyle@homebridge:~/.homebridge $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-legacy-plugins
Registering accessory 'homebridge-legacy-plugins.AD2USB'
Registering accessory 'homebridge-legacy-plugins.Carwings'
Registering accessory 'homebridge-legacy-plugins.ELKM1'
Registering accessory 'homebridge-legacy-plugins.FileSensor'
Registering accessory 'homebridge-legacy-plugins.GenericRS232Device'
Registering accessory 'homebridge-legacy-plugins.HomeMatic'
Registering accessory 'homebridge-legacy-plugins.HomeMaticThermo'
Registering accessory 'homebridge-legacy-plugins.HomeMaticWindow'
Registering accessory 'homebridge-legacy-plugins.HttpGarageDoorOpener'
Registering accessory 'homebridge-legacy-plugins.HttpHygrometer'
Registering accessory 'homebridge-legacy-plugins.HttpThermometer'
Registering accessory 'homebridge-legacy-plugins.Tesla'
Registering accessory 'homebridge-legacy-plugins.X10'
Registering accessory 'homebridge-legacy-plugins.mpdclient'
Registering platform 'homebridge-legacy-plugins.Domoticz'
Registering platform 'homebridge-legacy-plugins.HomeAssistant'
Registering platform 'homebridge-legacy-plugins.HomeSeer'
Registering platform 'homebridge-legacy-plugins.ISY'
Registering platform 'homebridge-legacy-plugins.LIFx'
Registering platform 'homebridge-legacy-plugins.SmartThings'
Registering platform 'homebridge-legacy-plugins.TelldusLive'
## Registering platform 'homebridge-legacy-plugins.ZWayServer'

/usr/local/lib/node_modules/homebridge/lib/server.js:129
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:129:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:25:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Function.Module.runMain (module.js:431:10)
    at startup (node.js:141:18)

**Comment by JSTYL** [comment]
Just wanted to report I solved this issue.  The problem was that I was missing the actual bridge configuration.  I think a lot of the manuals out there don't explain this very well but for those who are unaware you need to use the config.json format exactly as it's shown (there is a specific "accessories" and "platforms" section - the "platforms" is all you will use with SmartThings). 

**This is what was was missing and was causing my username error in the config.json file.**

> {
>   "bridge": {
>      "name": "Homebridge",
>         "username": "CC:22:3D:E3:CE:30",       <----This can be the MAC of your Pi
>         "port": 51826,
>         "pin": "031-45-154"                                <---- I'd change this from the default value
>     },

**This is what the final config.json layout should look like if you are only using SmarthThings with Homebridge.**  (The description text can be altered as desired)

> {
>     "bridge": {
>         "name": "Homebridge",
>         "username": "CC:22:3D:E3:CE:30",
>         "port": 51826,
>         "pin": "031-45-154"
>     },
> 
>   "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",
> 
>   "description": "JSON API",
>     "platforms": [{
>         "platform": "SmartThings",
>         "name": "SmartThings",
>         "app_id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
>         "access_token": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
>     }]
> }
